[package]
name = "fragula"
version = "0.1.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]
edition = "2018"

[dependencies]
luminance = "0.37.1"
luminance-glfw = "0.11.0"
luminance-derive = "0.5"
glsl = "1.2.0"
try-guard = "0.2.0"
wavefront_obj = "7.0.0"
